# Generated by Django 5.0 on 2025-03-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_customuser_buddies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_email_verified',
        ),
    ]
