# Generated by Django 5.1.3 on 2025-03-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_remove_customuser_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pic/avatar.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
