# Generated by Django 5.1.3 on 2025-03-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/profile_pic/avatar.jpg', null=True, upload_to='media/profile_pictures/'),
        ),
    ]
