# Generated by Django 5.0 on 2025-03-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='background_photo',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
