# Generated by Django 5.0 on 2025-03-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0007_customuser_background_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='background_photo',
        ),
    ]
