# Generated by Django 5.1.3 on 2025-03-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
