# Generated by Django 5.0 on 2025-03-05 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutevent',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutevent',
            name='participants',
            field=models.ManyToManyField(related_name='participated_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
