# Generated by Django 5.0 on 2025-03-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutevent',
            name='date',
        ),
        migrations.AddField(
            model_name='workoutevent',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
